batch_size: 16
dropout_rate: 0.2
epochs: 100
experiment_name: document_image_MLclassification
hidden_units:
- 1024
input_shape:
- 224
- 224
- 3
learning_rate: 0.001
loss_function: binary_crossentropy
optimizer: adam
run_name: cnn_model
