batch_size: 16
dropout_rate: 0.2
epochs: 100
experiment_name: document_image_classification
hidden_units:
- 1024
input_shape:
- 224
- 224
- 3
learning_rate: 0.001
loss_function: categorical_crossentropy
optimizer: adam
run_name: vgg_model
